export const MODIFY_ENGINE_PROP = "MODIFY_ENGINE_PROP";
export const UPDATE_PLATEAU_STATE = "UPDATE_PLATEAU_STATE";
export const FETCH_ENGINE_DATA = "FETCH_ENGINE_DATA";
export const MODIFY_VISUALS = "MODIFY_VISUALS";
